name: test wish list
public class WishListTest extends TestBase {

    @BeforeEach
    public void setUp() {
        mainSetUp();
        wishlist = new Wishlist(driver);
        filters = new Filters(driver);
        size = new Size(driver);
        collection = new Collection(driver);
        basket = new Basket(driver);
